### ISSUE TITLE
F: Add Testing. Then onboard CI. Then CD. 

### ISSUE THREAD

**Issue by ErikPlachta** [ErikPlachta/Calendari#74]
## When branches pushed to develop and main, CI execution runs to verify integrity of all tests

---

### Testing - jest.js 

- [ ] Login
- [ ] Signup
- [ ] Schedule
- [ ] User CRUD
- [ ] Business CRUD
- [ ] Others?

### CI - evaluate.yml

- [x] Develop
- [x] Main

### CD - deploy.yml

- [ ] On a test environment 
- [ ] On live environment

**Comment by ErikPlachta** [comment]
@NicaVulcan @mmlawton15 FYI

The next goal for me on this project is to onboard Continual Integration and testing with Jest. 

My plan is to research and frame it in this week on a test branch. 
> After it's working in MVP, I'll let you know so we can review as a team.  

---

Here's a Link to 100 second explication for a refresher on continual integration and why it's a priority --> https://youtu.be/scEDHsr3APg

**Comment by ErikPlachta** [comment]
- [x] #75 

## Onboarded CI for Installing Server/Client and Building Client - Ready to be merged.

```yml
- name: Install Client and Server
        run: npm install --if-present
      - name: Build Client
        run: npm run build --if-present
```
